version: '3.3'

services:

  api:
    container_name: ml_api
    restart: always
    build: ./api
    volumes: ['./api:/api']
    networks:
      - apinetwork
    expose:
      - "5000"
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]

  nginx:
    container_name: server
    restart: always
    build: ./server
    networks:
      - apinetwork
    expose:
      - "8080"
    ports:
      - "80:8080"

networks:
  apinetwork: